### ISSUE TITLE
Transform testing tracking issue

### ISSUE THREAD

**Issue by zou3519** [facebookresearch/functorch#45]
- [ ] vmap
- [ ] grad
- [ ] vjp
- [ ] vjp of vjp
- [ ] vjp of vmap
- [ ] vmap of vjp
- [ ] vmap of vmap

`grad` is really a special case of vjp. Do we need more tests for it?
- [ ] See if we can implement grad by calling vjp.
