### ISSUE TITLE
Eager transforms tracking issue

### ISSUE THREAD

**Issue by zou3519** [facebookresearch/functorch#57]
Many items taken from (fb-internal) https://fb.quip.com/RVR6Ab3W6FCZ#TIMACAXvwZ3

Transformable NN API
- [ ] Agree on if we can push `make_functional` as the initial API for users to work with.

vmap
- [ ] Determine a list of "top X most important" batching rules we should implement, where X is something like... 200? (#2)
- [ ] See if we can decompose all operations before going into vmap (#56)
    - [ ] Solve vmap(grad(foo)) decomposing into vmap-incompatible operations (#55)
- [ ] Figure out a better way to codegen plumbing (#54)

grad/vjp
- [ ] Come up with a plan for full coverage for the grad and vjp transforms (#42)

Infrastructure
- [ ] Improve the stack-based dispatching mechanism based on Ed's suggestion

New transforms
- [ ] [jvp] Add OpInfo testing for jvp and vmap+jvp
- [ ] [jvp] Confirm that vmap actually composes with jvp; and if not, propose changes to PyTorch forward-mode AD
- [ ] [jvp] Figure out how to make jvp compose with itself
- [ ] [xmap] Go understand how xmap works and if vmap is needed in its implementation
